sudo: false
language: go

go:
  - "1.13"
before_script:
  - go get

# before we deploy, we go build for all operating systems we would like to support
before_deploy:
  - mkdir -p release
  - "GOOS=linux  GOARCH=amd64 go build -o release/shelby-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o release/shelby-darwin-amd64"
  - "tar -cvzf shelby-darwin-amd64.tar.gz shelby-darwin-amd64"
  - "tar -cvzf shelby-linux-amd64.tar.gz shelby-darwin-amd64"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_API_KEY"
  file:
    - "release/shelby-linux-amd64"
    - "release/shelby-darwin-amd64"
    - "release/shelby-darwin-amd64.tar.gz"
    - "release/shelby-linux-amd64.tar.gz"
  skip_cleanup: true
  on:
    tags: true
