name: Starboy

on:
  push:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Statusoli
        uses: athul/statusoli@master
        env:
          STARGAZERS: ${{ github.event.repository.stargazers_count }}
          FORKERS: ${{ github.event.repository.forks_count }}
          IU_TITLE: ${{ github.event.issue.title }}
          IU_NUM: ${{ github.event.issue.number }}
          IU_ACTOR: ${{ github.event.issue.user.login }}
          IU_COM: ${{github.event.comment.body}}
          IU_BODY: ${{ github.event.issue.body }}
          PR_STATE: ${{ github.event.action }}
          PR_NUM: ${{ github.event.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        if: always()
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          status: ${{ job.status }}